---
apiVersion: v1
kind: Secret
metadata:
  name: maccabi-demo-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/LiorJanus/maccabi-demo-gitops